inherit_from: .rubocop_todo.yml

AllCops:
    NewCops: enable
    Include:
      - src/**/*

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
