AllCops:
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'tmp/**/*'
  NewCops: enable

Layout/ExtraSpacing:
  AllowForAlignment: false

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 150
  CountAsOne: ["array", "hash"]

Metrics/BlockLength:
  CountAsOne: ["array", "hash"]
  Exclude:
    - 'config/**/*'

Metrics/MethodLength:
  Max: 20
  CountAsOne: ["array", "hash"]

Metrics/ModuleLength:
  CountAsOne: ["array", "hash"]

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
