AWSTemplateFormatVersion: 2010-09-09

Description: 'Verification of CodePipeline variables'

Conditions:
  HasNot: !Equals [ 'true', 'false' ]

Resources:
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: play_with_aws_codepipeline_variables
      Description: This role is used by CodePipeline.
      AssumeRolePolicyDocument:
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - codepipeline.amazonaws.com
                - codebuild.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Tags:
        - Key: Project
          Value: play_with_aws
        - Key: Identifier
          Value: codepipeline_variables
        - Key: CmBillingGroup
          Value: play_with_aws_codepipeline_variables

  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/codebuild/play_with_aws_codepipeline_variables
      RetentionInDays: 7
      Tags:
        - Key: Project
          Value: play_with_aws
        - Key: Identifier
          Value: codepipeline_variables
        - Key: CmBillingGroup
          Value: play_with_aws_codepipeline_variables

  CodeBuildSetVariables:
    Type: AWS::CodeBuild::Project
    Properties:
      # プロジェクトの設定
      Name: pwa_codepipeline_variables_set_variables
      Description: Set variables for CodePipeline
      ConcurrentBuildLimit: 1
      # ソース
      Source:
        Type: CODEPIPELINE
        # BuildSpec
        BuildSpec: |
          version: 0.2
          env:
            exported-variables:
              - VARIABLES_SET_IN_CODEBUILD
          phases:
            build:
              commands: |
                export VARIABLES_SET_IN_CODEBUILD="Set in CodeBuild"
                echo ${VARIABLES_SET_IN_CODEBUILD}
      # 環境
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/standard:7.0"
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
      ServiceRole: !Ref CodePipelineRole
      TimeoutInMinutes: 5
      QueuedTimeoutInMinutes: 480
      # バッチ設定
      BadgeEnabled: false
      # アーティファクト
      Artifacts:
        Type: CODEPIPELINE
      # ログ
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Ref CloudWatchLogGroup
      ResourceAccessRole: !Ref CodePipelineRole
      Tags:
        - Key: Project
          Value: play_with_aws
        - Key: Identifier
          Value: codepipeline_variables
        - Key: CmBillingGroup
          Value: play_with_aws_codepipeline_variables
