AWSTemplateFormatVersion: 2010-09-09

Description: 'Verification of CodePipeline variables'

Conditions:
  HasNot: !Equals [ 'true', 'false' ]

Resources:
  NullResource:
    Type: 'Custom::NullResource'
    Condition: HasNot
