AWSTemplateFormatVersion: 2010-09-09

Description: 'Switch Role'

Conditions:
  HasNot: !Equals [ 'true', 'false' ]

Resources:
  Policy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: play_with_aws_switch_role
      Description: This policy is used to switch role
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - 's3:ListBucket'
            Resource: '*'
