AWSTemplateFormatVersion: 2010-09-09

Description: "CodePipeline for ECS by Blue/Green Deployment"

Conditions:
  HasNot: !Equals [ "true", "false" ]

Resources:
  DeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: play_with_aws_web_service_with_ecs_deploy
      Description: play_with_aws_web_service_with_ecs
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
                - "codedeploy.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeDeployRoleForECS
      Tags:
        - Key: Project
          Value: play_with_aws
        - Key: Identifier
          Value: web_service_with_ecs
        - Key: CmBillingGroup
          Value: play_with_aws_web_service_with_ecs

  KMSKeyForDeploy:
    Type: AWS::KMS::Key
    Properties:
      Description: play_with_aws_web_service_with_ecs_deploy
      Enabled: true # キーのタイプ
      KeyUsage: ENCRYPT_DECRYPT # キーの使用法
      KeySpec: SYMMETRIC_DEFAULT
      Origin: AWS_KMS # キーマテリアルオリジン
      MultiRegion: false # リージョンごと
      EnableKeyRotation: true # キーローテーション
      KeyPolicy: # キーの管理者 & キーの削除 & キーユーザー & 別のAWSアカウント
        Version: "2012-10-17"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - "kms:*"
            Resource: "*"
          - Sid: "Allow use of the key"
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt DeployRole.Arn
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
          - Sid: Allow attachment of persistent resources
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt DeployRole.Arn
            Action:
              - kms:CreateGrant
              - kms:ListGrants
              - kms:RevokeGrant
            Resource: "*"
            Condition:
              Bool:
                kms:GrantIsForAWSResource: "true"
      #BypassPolicyLockoutSafetyCheck: Boolean
      PendingWindowInDays: 7
      Tags:
        - Key: Project
          Value: play_with_aws
        - Key: Identifier
          Value: web_service_with_ecs
        - Key: CmBillingGroup
          Value: play_with_aws_web_service_with_ecs

  KMSKeyForDeployAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/play_with_aws_web_service_with_ecs_deploy
      TargetKeyId: !Ref KMSKeyForDeploy

