AWSTemplateFormatVersion: 2010-09-09

Description: "CodePipeline for ECS by Blue/Green Deployment"

Conditions:
  HasNot: !Equals [ "true", "false" ]

Resources:
  NullResource:
    Type: Custom::NullResource
    Condition: HasNot
