AWSTemplateFormatVersion: 2010-09-09

Description: "CodePipeline for ECS by Blue/Green Deployment"

Conditions:
  HasNot: !Equals [ "true", "false" ]

Resources:
  DeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: play_with_aws_web_service_with_ecs_deploy
      Description: play_with_aws_web_service_with_ecs
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
                - "codedeploy.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeDeployRoleForECS
      Tags:
        - Key: Project
          Value: play_with_aws
        - Key: Identifier
          Value: web_service_with_ecs
        - Key: CmBillingGroup
          Value: play_with_aws_web_service_with_ecs

  KMSKeyForDeploy:
    Type: AWS::KMS::Key
    Properties:
      Description: play_with_aws_web_service_with_ecs_deploy
      Enabled: true # キーのタイプ
      KeyUsage: ENCRYPT_DECRYPT # キーの使用法
      KeySpec: SYMMETRIC_DEFAULT
      Origin: AWS_KMS # キーマテリアルオリジン
      MultiRegion: false # リージョンごと
      EnableKeyRotation: true # キーローテーション
      KeyPolicy: # キーの管理者 & キーの削除 & キーユーザー & 別のAWSアカウント
        Version: "2012-10-17"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - "kms:*"
            Resource: "*"
          - Sid: "Allow use of the key"
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt DeployRole.Arn
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
          - Sid: Allow attachment of persistent resources
            Effect: Allow
            Principal:
              AWS:
                - !GetAtt DeployRole.Arn
            Action:
              - kms:CreateGrant
              - kms:ListGrants
              - kms:RevokeGrant
            Resource: "*"
            Condition:
              Bool:
                kms:GrantIsForAWSResource: "true"
      #BypassPolicyLockoutSafetyCheck: Boolean
      PendingWindowInDays: 7
      Tags:
        - Key: Project
          Value: play_with_aws
        - Key: Identifier
          Value: web_service_with_ecs
        - Key: CmBillingGroup
          Value: play_with_aws_web_service_with_ecs

  KMSKeyForDeployAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/play_with_aws_web_service_with_ecs_deploy
      TargetKeyId: !Ref KMSKeyForDeploy

  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      # プロジェクトの設定
      Name: play_with_aws_web_service_with_ecs
      Description: play_with_aws_web_service_with_ecs
      BadgeEnabled: false
      ConcurrentBuildLimit: 1
      # ソース
      Source:
        Type: CODEPIPELINE
        # Build Spec
        BuildSpec: buildspec.yaml
      # 環境
      ServiceRole: !Ref DeployRole
      TimeoutInMinutes: 60
      QueuedTimeoutInMinutes: 480
      Environment:
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: ENVIRONMENT
            Value: production
            Type: PLAINTEXT
      # アーティファクト
      Artifacts:
        Type: CODEPIPELINE
        EncryptionDisabled: false
      EncryptionKey: !Ref KMSKeyForDeployAlias
      Cache:
        Type: NO_CACHE
      # ログ
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
        S3Logs:
          Status: DISABLED
      ResourceAccessRole: !Ref DeployRole
      Visibility: PRIVATE
      Tags:
        - Key: Project
          Value: play_with_aws
        - Key: Identifier
          Value: web_service_with_ecs
        - Key: CmBillingGroup
          Value: play_with_aws_web_service_with_ecs

  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: play_with_aws_web_service_with_ecs
      ComputePlatform: ECS
      Tags:
        - Key: Project
          Value: play_with_aws
        - Key: Identifier
          Value: web_service_with_ecs
        - Key: CmBillingGroup
          Value: play_with_aws_web_service_with_ecs

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      # デプロイグループの詳細
      DeploymentGroupName: ecs # デプロイグループ名
      ApplicationName: !Ref CodeDeployApplication # アプリケーション名
      ServiceRoleArn: !GetAtt DeployRole.Arn # サービスロールARN
      ## デプロイ設定
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      BlueGreenDeploymentConfiguration:
        DeploymentReadyOption:
          ActionOnTimeout: CONTINUE_DEPLOYMENT
        # GreenFleetProvisioningOption:
        #   Action: COPY_AUTO_SCALING_GROUP
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 5
      AutoRollbackConfiguration:
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE
          - DEPLOYMENT_STOP_ON_REQUEST
      # 環境設定
      ECSServices:
        - ClusterName: !ImportValue play-with-aws-web-service-with-ecs-cluster-name # ECSクラスター名
          ServiceName: !ImportValue play-with-aws-web-service-with-ecs-service-name # ECSサービス名
      # Load Balancer
      LoadBalancerInfo:
          TargetGroupPairInfoList:
            - ProdTrafficRoute:
                ListenerArns:
                  - !ImportValue play-with-aws-web-service-with-ecs-listener
              TargetGroups:
                - Name: !ImportValue play-with-aws-web-service-with-ecs-target-group-for-blue-name
                - Name: !ImportValue play-with-aws-web-service-with-ecs-target-group-for-green-name
              # TestTrafficRoute:
              #   TrafficRoute
      # トリガー
      # TriggerConfigurations:
      #   - TriggerConfig
      # アラーム
      # AlarmConfiguration:
      #   AlarmConfiguration
      # OnPremisesTagSet:
      #   OnPremisesTagSet
      Tags:
        - Key: Project
          Value: play_with_aws
        - Key: Identifier
          Value: web_service_with_ecs
        - Key: CmBillingGroup
          Value: play_with_aws_web_service_with_ecs
