AWSTemplateFormatVersion: 2010-09-09

Description: 'Web Service with ECS'

Conditions:
  HasNot: !Equals [ 'true', 'false' ]

Outputs:
  CodeStarConnectionArnForGitHub:
    Description: Arn of CodeStarConnection for GitHub
    Value: !GetAtt GitHubConnection.ConnectionArn
    Export:
      Name: play-with-aws-web-service-with-ecs-code-star-connection

Resources:
  GitHubConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: pwa_web_service_with_ecs
      ProviderType: GitHub
      Tags:
        - Key: Project
          Value: play_with_aws
        - Key: Identifier
          Value: web_service_with_ecs
        - Key: CmBillingGroup
          Value: play_with_aws_web_service_with_ecs
